

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
        USER_ID int(6) NOT NULL,
		UserName varchar(20) NOT NULL,
        Password varchar(100) NOT NULL,
        AUTHORITY_ID int(6) NOT NULL,
        ENABLED varchar(20) NOT NULL,
        PRIMARY KEY (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



	
DROP TABLE IF EXISTS AUTHORITIES;
CREATE TABLE AUTHORITIES (
        AUTHORITY_ID int(6) NOT NULL AUTO_INCREMENT,
        AUTHORITY varchar(20) NOT NULL,
        PRIMARY KEY (AUTHORITY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into USERS values(1, 'dhoni', '78d7a82604de80d2b191e92a96d23a2803c0a0e910a32a6744e3ecd41e4da4cf', 1, 'true');
insert into AUTHORITIES values(1, 'ROLE_ADMIN');
insert into AUTHORITIES values(2, 'ROLE_MEMBER');

ALTER TABLE USERS
ADD FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITIES(AUTHORITY_ID) ON DELETE
CASCADE ON UPDATE CASCADE;